// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuehjnjmstpltmrbxgij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZWhqbmptc3RwbHRtcmJ4Z2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzM3NDEsImV4cCI6MjA2NjAwOTc0MX0.0zGkf3embfbQPpz4IxOYGu0sawJzz3RYfA2lmi5zbz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);