// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtvfuaehhilbyhtakoel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dmZ1YWVoaGlsYnlodGFrb2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDcwMDksImV4cCI6MjA2NTQ4MzAwOX0.mdRqR7woJhEWgNlXYGxBCUKcSoToIzPSsC4iNW6A3oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);